import { z } from 'zod';
import { db, editSchema, handle, HttpError, input, json, limit, passwordField, publicMetadata, publicPost, publishedPost, recruitmentValues } from '../../../../lib/server';
import { verifyPassword } from '../../../../lib/password';
type Context={params:Promise<{id:string}>};
export const dynamic='force-dynamic';
async function authenticated(request:Request,id:string,password:string){await limit(request,'password',30);const post=await publishedPost(id);if(!await verifyPassword(password,post.salt,post.password_hash))throw new HttpError(403,'비밀번호가 일치하지 않습니다.');return post;}
export async function GET(_request:Request,context:Context){return handle(async()=>{const {id}=await context.params;return json({post:publicMetadata(await publishedPost(id))});});}
export async function POST(request:Request,context:Context){return handle(async()=>{const {password}=z.object({password:passwordField}).parse(await input(request));const {id}=await context.params;const post=await authenticated(request,id,password);return json({post:publicPost(post)});});}
export async function PATCH(request:Request,context:Context){return handle(async()=>{const data=editSchema.parse(await input(request));const {id}=await context.params;const post=await authenticated(request,id,data.password);const status=post.category==='news'?'pending':'published';const [recruitmentStatus,deadline,headcount,roles]=recruitmentValues(data,post.category);await db().prepare('UPDATE posts SET title=?,content=?,status=?,recruitment_status=?,deadline=?,headcount=?,roles=?,updated_at=? WHERE id=?').bind(data.title,data.content,status,recruitmentStatus,deadline,headcount,roles,Date.now(),id).run();return json({ok:true,status});});}
export async function DELETE(request:Request,context:Context){return handle(async()=>{const {password}=z.object({password:passwordField}).parse(await input(request));const {id}=await context.params;await authenticated(request,id,password);await db().prepare('DELETE FROM posts WHERE id=?').bind(id).run();return json({ok:true});});}
